@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

interface Storage <<Interface>>
interface UserPrefsStorage <<Interface>>
interface EateryListStorage <<Interface>>
interface FeedListStorage <<Interface>>

class JsonAdaptedEatery
class JsonAdaptedFeed
class JsonAdaptedFeedPost
class JsonAdaptedReview
class JsonAdaptedTag
class JsonEateryListStorage
class JsonFeedListStorage
class JsonUserPrefsStorage
class JsonSerializableEateryList
class JsonSerializableFeedList

StorageManager ..|> Storage
StorageManager o--> UserPrefsStorage
StorageManager o--> EateryListStorage
StorageManager o--> FeedListStorage

JsonUserPrefsStorage ..|> UserPrefsStorage
JsonEateryListStorage ..|> EateryListStorage
JsonFeedListStorage ..|> FeedListStorage

JsonEateryListStorage ..> JsonSerializableEateryList
JsonSerializableEateryList --> JsonAdaptedEatery
JsonAdaptedEatery --> JsonAdaptedReview
JsonAdaptedEatery --> JsonAdaptedTag

JsonFeedListStorage ..> JsonSerializableFeedList
JsonSerializableFeedList --> JsonAdaptedFeed
JsonAdaptedFeed --> JsonAdaptedFeedPost
@enduml
